# version: '3.8' # (optional) Modern Docker Compose (v2+) defaults to a recent version automatically.

services:
  sonarqube-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonarqube-db:/var/lib/postgresql/data
    networks:
      - java-jenk_sonarnet

  sonarqube:
    image: sonarqube:community
    depends_on:
      - sonarqube-db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
    networks:
      - java-jenk_sonarnet

volumes:
  sonarqube-db:
  sonarqube-data:
  sonarqube-logs:

networks:
  java-jenk_sonarnet:
    driver: bridge
